[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block-mesh = "0.2.0"
noise = { git = "https://github.com/Razaekel/noise-rs" }
bevy_math = "0.8.1"
